#
# GMT 6.5.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 10p,Helvetica,black
FONT_LABEL                     = 12p,Helvetica,black
#
# FORMAT Parameters
#
FORMAT_GEO_MAP                 = ddd.xx
#
# MAP Parameters
#
MAP_DEGREE_SYMBOL              = none
#
# PostScript Parameters
#
PS_CHAR_ENCODING               = Standard
PS_LINE_CAP                    = round
PS_LINE_JOIN                   = round
